In [5]:
import requests
import json
import pandas as pd


apiKey = 's6MhiJfSYMZHpDA2qGtspeI3XdffZ3F5dgWdK8Rl' 
foodID = '1750354' 

def nutrient_API(apiKey, foodID):
    #calls get api and json load
    api_resp = json.loads(requests.get('https://api.nal.usda.gov/fdc/v1/' + foodID + '?api_key=' + apiKey).text)
    #only return nutrition information
    api_nutrients = api_resp['foodNutrients']
    #first entry is its description, foodID, and database entry type
    nutrientDict = {"FoodID": [api_resp['description'],foodID, api_resp['dataType']]}

    for items in api_nutrients:
        if 'amount' in items:
            #each entry includes nutrient name, nutrient id, amount, and its respective unit
            nutrientDict.update({(items['nutrient']['name']): [(items['nutrient']['id']),
                (items['amount']),(items['nutrient']['unitName'])]})
        #print(nutrientDict)
    return(nutrientDict)


def trypfunc(foodID):
    dataframe = pd.DataFrame(nutrient_API(apiKey, foodID))
    tryp_g=(dataframe['Tryptophan'][1])
#does some more stuff
    return trypfunc

In [6]:
df = pd.DataFrame(nutrient_API(apiKey, foodID))

In [7]:
df.head()

,FoodID,Water,Energy (Atwater General Factors),Energy (Atwater Specific Factors),Nitrogen,Protein,Total lipid (fat),Ash,"Carbohydrate, by difference","Fiber, total dietary",...,"Vitamin A, RAE","Carotene, beta","Carotene, alpha","Carotene, gamma","Cryptoxanthin, beta","Cryptoxanthin, alpha",Lycopene,cis-Lutein/Zeaxanthin,Lutein,Zeaxanthin
0,"Tomato, roma",1051,2047,2048,1002,1003,1004,1007,1005,1079,...,1106,1107,1108,1118,1120,2032,1122,1161,1121,1119
1,1750354,94.73,21.9574,18.9544,0.1113,0.695625,0.425,0.3119,3.83747,0.9706,...,23.9,275.5,0.875,2.125,19.0625,9.625,2862.56,0,56,0
2,Foundation,g,kcal,kcal,g,g,g,g,g,g,...,µg,µg,µg,µg,µg,µg,µg,µg,µg,µg